### ISSUE TITLE
ibeetl 2.2.8 include、layout 临时变量不能被读取

### ISSUE THREAD

**Issue by ewill** [javamonkey/beetl2.0#214]
在Beetl官方文档里面的例子：
<% layout("/inc/layout.html",{title:'主题'}) {} %>
但是在layout.html里面不能读取title变量，${title}后台说变量未定义
我不确定这个是不是bug，可能是我的配置错了（刚刚开始用ibeetl）？

**Comment by javamonkey** [comment]
我这边看并没有这个问题，也没有其他人反馈这个问题，我觉得是你那边错了，你最好贴一下整个错误提示，我好分析。

我现在只能猜测，你的代码直接渲染了layout.html 页面，所以当然没有title，你应当渲染你的主页面，而不是layout 页面

**Comment by ewill** [comment]
举个栗子：
前提：被包含的页面路径正确。

index.html 首页，里面包含我要输出的数据，因为特殊原因，输出数据这部分代码放在别的页面上。
data.html 数据输出页面

<div class="container">
    <% include ('data.html', { 'title' : 'test title' }) {} %>
</div>

我是这样包含的，可是在data.html页面中，这个变量 ${title} 后台说未定义

**Comment by javamonkey** [comment]
你渲染的是index页面吗？  我周日刚完成一个demo，用来演示beetlsql和beetl，用的是2.2.8，一切正常啊？ 这是代码：

https://git.oschina.net/xiandafu/park/blob/master/oss/src/main/webapp/WEB-INF/views/park/index.btl/?dir=0&filepath=oss/src/main/webapp/WEB-INF/views/park/index.btl&oid=6c8f54f87612b9037c64cc6969dcc5a942fefea3&sha=040d55a45c5febdf1b38064848c7bdfedd9afaa9

**Comment by ewill** [comment]
你的链接跳到404页面了哦

**Comment by javamonkey** [comment]
哦，这个属性是私有的，所以你点不开
