### ISSUE TITLE
ClasspathResourceLoader exit 方法有误

### ISSUE THREAD

**Issue by javamonkey** [javamonkey/beetl2.0#222]
@Override
	public boolean exist(String key)
	{
		return this.classLoader.getClass().getResource(root + key) != null;
	}

应该是 this.classLoader.getResource(root + key) != null;

**Comment by kingsmiler** [comment]
Spring的new ClassPathResource(key).exists() 使用的也是楼主所说的this.classLoader.getResource。

对于该问题楼主注释为『 不兼容，暂时不能修改』，请问楼主是为了兼容什么样的资源或场景，才暂时不修改？

**Comment by javamonkey** [comment]
主要是有不少项目已经使用了，如果需要建议参考源码重新做一个吧

**Comment by javamonkey** [comment]
你获取资源用的是  loader.getclass().getResource()...
判断exist 用的是   loader.classLoader.getClass().getResource().

另外，兼容俩种loader方式，这样可以升级

**Comment by javamonkey** [comment]
解决
