### ISSUE TITLE
文档错误。

### ISSUE THREAD

**Issue by onilylove** [javamonkey/beetl2.0#229]
![image](https://cloud.githubusercontent.com/assets/6722755/13943590/b31e27ce-f038-11e5-8ccf-a0a6fc685c26.png)
![image](https://cloud.githubusercontent.com/assets/6722755/13943599/c0021d1a-f038-11e5-85b5-d1396108a503.png)
文文档中描述有问题。

**Comment by javamonkey** [comment]
thanks
