### ISSUE TITLE
spring 集成增加一个local 国际化函数

### ISSUE THREAD

**Issue by javamonkey** [javamonkey/beetl2.0#234]

**Comment by javamonkey** [comment]
其他还包括jfinal

**Comment by javamonkey** [comment]
参考：

`<%
/*
spring 国际化标签
<#message
	code="message文件中的key，必填"
	arguments="message消息参数"
	argumentSeparator="参数分隔符，默认值：','"
/>
*/
var classType = @Class.forName("org.springframework.web.servlet.support.RequestContext");
var reqClass = @Class.forName("javax.servlet.http.HttpServletRequest");
var con = @classType.getConstructor(reqClass);
var requestContext = @con.newInstance(request);

var argSep = isNotEmpty(tag.argumentSeparator)?tag.argumentSeparator:',';
var text = "";
if(isNotEmpty(tag.arguments)){
	var args = strutil.split(tag.arguments,argSep);
	text = @requestContext.getMessage(tag.code, args);
} else {
    text = @requestContext.getMessage(tag.code);
}
print(text);
%>
`

**Comment by guoai2015** [comment]
感觉标签写起来不如函数简单，改造了一下，这是函数：
<%
/*
spring 国际化函数
message(para0,para1,para2)
	para0="message文件中的key，必填"
	para1="message消息参数"
	para2="参数分隔符，默认值：','"
*/
var classType = @Class.forName("org.springframework.web.servlet.support.RequestContext");
var reqClass = @Class.forName("javax.servlet.http.HttpServletRequest");
var con = @classType.getConstructor(reqClass);
var requestContext = @con.newInstance(request);

var argSep = isNotEmpty(para2)?para2:',';
var text = "";
if(isNotEmpty(para1)){
	var args = strutil.split(para1,argSep);
	text = @requestContext.getMessage(para0, args);
} else {
    text = @requestContext.getMessage(para0);
}
return text;
%>

**Comment by javamonkey** [comment]
http://ibeetl.com/community/?/article/92
