### ISSUE TITLE
实现适配多套定界符

### ISSUE THREAD

**Issue by guoai2015** [javamonkey/beetl2.0#238]
需求背景：脚手架项目最早用的<%%>来做定界符。现在大家都在用@和换行符，感觉更高大上。目前beetl只能同时支持一套定界符。由于脚手架项目已经成型，更改起来工作量比较大。而又对高大上的用法难以割舍。为此提出此需求。

想法：同一个模板文件中适配一套定界符就可以，解析includ、tag、function文件的时候要重新检索定界符。

**Comment by javamonkey** [comment]
include 不支持，但可以重新实现YourIncludeTag，来完成，Tag，Function可以了，通过修改配置文件指定新的定界符号，beetl2.4.0 版本新功能
