### ISSUE TITLE
项目首页pom.xml文件出现异常信息

### ISSUE THREAD

**Issue by kingsmiler** [javamonkey/beetl2.0#244]
https://github.com/javamonkey/beetl2.0/blob/master/pom.xml

	<modules>
		<module>beetl-core</module>
<<<<<<< HEAD
		
=======
		<module>beetl-performance</module>
>>>>>>> 9a8cafcdc0904850a7a19a4111ebe7b65da4ee72
	</modules>

**Comment by javamonkey** [comment]
用core下面的工程
