### ISSUE TITLE
GroupTemplate.loadTemplate(String) 方法没有对无效资源路径的处理

### ISSUE THREAD

**Issue by greenlaw110** [javamonkey/beetl2.0#261]
`GroupTemplate.loadTemplate(String)`在任何情况下都会返回一个`Template`实例，而且没有办法通过`Template`类来检查资源路径是否有效。这样就把错误处理推迟到了render的时候，违背了[快速失效原则](https://en.wikipedia.org/wiki/Fail-fast)

**Comment by javamonkey** [comment]
groupTemplate().getResourceLoader().exist(resourceId)
