### ISSUE TITLE
要求在BeetlGroupUtilConfiguration中提供sharedVars属性的Properties输入方式.

### ISSUE THREAD

**Issue by juqkai** [javamonkey/beetl2.0#272]
要求在BeetlGroupUtilConfiguration中提供sharedVars属性的Properties输入方式.

添加理由:
在与spring进行整合中, 有些url路径需要在页面中使用. 一般都会写在properties中. 
在模板中都是通用的, 所以使用sharedVars来进行存储. 但configuration中只有注入map的方式. 这样的话, 每加一项就需要在配置文件中添加一条. 不利于扩展.
spring中可以使用<util:properties id="xxx" location="classpath:xxx.properties"/>直接解析出properties

**Comment by javamonkey** [comment]
spring 集成支持这个功能 ，参考：http://ibeetl.com/guide/beetl.html#_springmvc集成高级

提到了 sharedVars
