### ISSUE TITLE
咨询，如何设置默认值，如果值中包括 {或者}或报错，请问需要如何设置

### ISSUE THREAD

**Issue by ming300** [javamonkey/beetl2.0#321]
`
var pdfJson=${full_pdf_json!"{}"};
`

如上，这个表达式会报错 TOKEN_ERROR
请问需要如何设置为 默认值是一个 json的文本 或者 是一个 包含 { 或者 } 的文本 ？

**Comment by javamonkey** [comment]
用 ‘\’
var pdfJson=${full_pdf_json!"{\}"};
