### ISSUE TITLE
CompositeResourceLoader加载器遇到解析出错时,因BeetlException.resourceId不对而异常丢失的问题

### ISSUE THREAD

**Issue by yeriwei** [javamonkey/beetl2.0#322]
1. 在用CompositeResourceLoader资源加载的时候，由于有些带前缀自定义如classpath: demo:前缀的方式。
2. 当demo:前缀资源解析出错时，ConsoleErrorHandler.processExcption（）方法中定位模板行内容时用的是Resource res = resLoader.getResource(ex.resourceId);   BeetlException.resourceId是不带前缀的，变成默认加载器获取模板资源，失败，导致异常丢失的问题？

**Comment by javamonkey** [comment]
完成，请更新到新版本
