### ISSUE TITLE
怎么向集合中添加元素

### ISSUE THREAD

**Issue by zhuchaoming** [javamonkey/beetl2.0#340]
尝试了下面几种办法，但是都出现错误：
一：
<%
        var arr1 = [1,2,3];
        var arr2 = [];
        var index = 0;
        for(item in arr1){
            arr2[index++] = item;
        }
%>

错误信息：
>>04:10:24:属性获取异常(ATTRIBUTE_INVALID):[] 位于6行 资源:<% ...
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
3| var arr2 = [];
4| var index = 0;
5| for(item in arr1){
6| arr2[index++] = item;
7| }
8|%>
java.util.ArrayList.rangeCheck(ArrayList.java:653)
java.util.ArrayList.set(ArrayList.java:444)
org.beetl.core.om.ObjectAA.setValue(ObjectAA.java:125)
org.beetl.core.statement.VarRefAssignStatement.execute(VarRefAssignStatement.java:70)
org.beetl.core.statement.BlockStatement.execute(BlockStatement.java:68)
org.beetl.core.statement.ForStatement.execute(ForStatement.java:144)
org.beetl.core.statement.Program.execute(Program.java:70)
org.beetl.core.Template.renderTo(Template.java:137)
org.beetl.core.Template.renderTo(Template.java:90)
org.beetl.core.Template.render(Template.java:77)
org.bee.tl.online.TestServlet.render(TestServlet.java:302)
org.bee.tl.online.TestServlet.testTemplate(TestServlet.java:293)
org.bee.tl.online.TestServlet.doPost(TestServlet.java:243)
javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.j
---------------------------------------------------------------------------------------------------------

二：
<%
        var arr1 = [1,2,3];
        var arr2 = [];
        
        for(item in arr1){
            arr2.add(item);
        }
%>

错误信息：
>>04:06:53:该方法未注册(FUNCTION_NOT_FOUND):arr2.add 位于6行 资源:<% ...
3| var arr2 = [];
4| 
5| for(item in arr1){
6| arr2.add(item);
7| }
8|%>
--------------------------------------------------------------------------------------------------------

三：
<%
        var arr1 = [1,2,3];
        var arr2 = @new java.util.ArrayList<>();
        // 或者
       /*@java.util.List arr2 = new java.util.ArrayList<>();*/

        for(item in arr1){
            arr2.add(item);
        }
%>

错误信息：
>>04:23:37:缺少符号(PARSER_MISS_ERROR):java 位于3行 资源:<% ...
缺少输入 ';' 在 'java'
1|<%
2| var arr1 = [1,2,3];
3| var arr2 = @new java.util.ArrayList<>();
4| // 或者
5| /*@java.util.List arr2 = new java.util.ArrayList<>();*/
=============

正确的写法是什么？

**Comment by javamonkey** [comment]
@arr1.add(),   @符号表示java调用，因此你可以像java api那样调用， 另外是提供内置方法
array.add(arr1,xxx)
