### ISSUE TITLE
groupTemplate.setSharedVars()可否考虑支持多次set

### ISSUE THREAD

**Issue by jadyer** [javamonkey/beetl2.0#351]
版本：2.8.1
操作：假如在 static{} 中初始化一些共享变量，接着render之前又setSharedVars()
结果：static块里初始化的共享变量被冲掉
建议：groupTemplate.setSharedVars()可否考虑支持多次set，请大赋考虑下，谢谢~

**Comment by javamonkey** [comment]
下个版本发布
