### ISSUE TITLE
关于自定义标记 GeneralVarTagBinding 的binds 取值混乱现象

### ISSUE THREAD

**Issue by trilobita-org** [javamonkey/beetl2.0#353]
LinkedHashMap<String,Integer> linkedHashMap=new LinkedHashMap();
 linkedHashMap.put("a1",0);
linkedHashMap.put("a2",1);
this.mapName2Index(linkedHashMap);

this.bind("a1","你好1");
this.bind("a2","你好2");

this.doBodyRender();

我在模版中如果不使用${a1},直接使用两个${a2} 取的值并未获取到a2的变量值，得到的结果是两个a1的变量值

**Comment by javamonkey** [comment]
能贴出完整代码以方便我重现这个功能吗？或者给一个最简单的git项目地址，我拿下来运行

**Comment by javamonkey** [comment]
抱歉，回答晚了，用法错误了，应该是
`
<#NaviTree var="a1,a2">
   ${a2} ${a2}
</#NaviTree>

`

也就是标签本身必须声明一下变量

另外，标签实现代码如下

`
public class NaviTree extends GeneralVarTagBinding {
    @Autowired
    private RestTemplate restTemplate;
    @Override
    public void render() {

        //这里的内容为空，不支持注入的方式
        System.out.println(restTemplate);

      
        this.binds("xxxx",1234);
        this.doBodyRender();

    }
}
`

这个标签绑定了俩个变量，其值是xxxx和1234，然后，在模板标签中声明了a1,a2俩个变量分别对应（按照顺讯对应，叫什么变量都行，模板编写者使用任何变量名而不是标签实现着规定的变量）

参考官网文档看如何实现绑定变量标签
