### ISSUE TITLE
是否能在定义标记的类中，支持spring 注入机制

### ISSUE THREAD

**Issue by trilobita-org** [javamonkey/beetl2.0#355]
public class NaviTree extends GeneralVarTagBinding {
    @Autowired
    private RestTemplate restTemplate;
    @Override
    public void render() {

        //这里的内容为空，不支持注入的方式
        System.out.println(restTemplate);

    }
}

**Comment by javamonkey** [comment]
支持,参考 https://gitee.com/xiandafu/Spring-Boot-2.0-Samples/blob/master/4_views/ch4.beetl/src/main/java/com/bee/sample/ch4/conf/BeetlExtConfig.java
