### ISSUE TITLE
磁盘根目录下运行程序BeetlUtil.getWebRoot()报空指针。

### ISSUE THREAD

**Issue by think-gem** [javamonkey/beetl2.0#356]
https://github.com/javamonkey/beetl2.0/blob/683ad4fb3c372697e867980b30319a2f3490d128/beetl-core/src/main/java/org/beetl/core/misc/BeetlUtil.java#L279

**Comment by javamonkey** [comment]
看代码确实是，下次修复这个代码

**Comment by javamonkey** [comment]
这个方法是针对Web项目结构，按理说，不应该会出现这个问题
