### ISSUE TITLE
未找到属性(ATTRIBUTE_NOT_FOUND) 但还是把未处理完的页面返回给浏览器了，这种情况如何处理？

### ISSUE THREAD

**Issue by zhaobingss** [javamonkey/beetl2.0#369]
如何把这个错误以异常的形式抛出，而不是继续向浏览器输出

**Comment by javamonkey** [comment]
默认采用ConsoleErrorHanlder来处理，可以换一种，比如ReThrowConsoleErrorHandler, WebErrorHandler，参考官网功能
3.9. 自定义错误处理器。

**Comment by zhaobingss** [comment]
看了下浏览器的返回内容,怀疑和下面的Writter有关系
public void processExcption(BeetlException ex, Writer writer){}
如果渲染到一半有异常，使用这个writer把异常信息写入到浏览器端的话，其实是把当前的异常信息append到渲染完的那一半的模板的后面，猜测渲染模板的writter和异常处理的writter用的地同一个，
看来就算自定义的ErrorHandler也解决不了问题呀

**Comment by zhaobingss** [comment]
经反复测试，确实是如上的问题，WebErrorHandler也一样存在这个问题
