### ISSUE TITLE
视图渲染问题

### ISSUE THREAD

**Issue by zhaobingss** [javamonkey/beetl2.0#370]
话说在web环境下，不是应该将视图渲染完毕再往流里写吗，现在是，一边渲染一边写，如果中间出了问题，会把模板的一部分渲染到前端，这样好么，就算向前端输出错误信息，也不一定能显示出来呀。

**Comment by javamonkey** [comment]
一般情况，考虑到web页面比较多，都会有缓冲，并不会等页面渲染完毕后，再输出到客户端。无论你用什么技术，都会有这种问题。你要避免这个问题，可以设置交大的缓冲。

另外，页面开发过程中出错了无所谓。如果线上还有错误，这样好吗？
