### ISSUE TITLE
StringTypeHandler oracle Clob is null

### ISSUE THREAD

**Issue by wung** [javamonkey/beetl2.0#376]
`public Object getValue(TypeParameter typePara) throws SQLException {
        ResultSet rs = typePara.rs;
        int index = typePara.index;
        if (typePara.dbName.equals("oracle")) {
            int type = typePara.meta.getColumnType(index);
            Reader r;
            switch(type) {
            case 2005:
                r = rs.getClob(index).getCharacterStream();
                return LobKit.getString(r);
            case 2011:
                r = rs.getNClob(index).getCharacterStream();
                return LobKit.getString(r);
            default:
                return rs.getString(index);
            }
        } else {
            return rs.getString(index);
        }
    }`

if rs.getClob(index) is null ,error info :
java.lang.NullPointerException
	at org.beetl.sql.core.mapping.type.StringTypeHandler.getValue(StringTypeHandler.java:21)

**Comment by wung** [comment]
@javamonkey

**Comment by javamonkey** [comment]
这是beetlsql 问题，而且，现在代码并不是这样的
