### ISSUE TITLE
如何输出转义字符

### ISSUE THREAD

**Issue by dongtc** [javamonkey/beetl2.0#378]
类似ejs的：

`Escaped output with <%= %> (escape function configurable)`
`Unescaped raw output with <%- %>`

大部分模板引擎都是默认转义，但beetl我在文档里也没找到简单的方法

只看到这个`sputil.html(String input)`

**Comment by javamonkey** [comment]
用\, 搜索escape

**Comment by dongtc** [comment]
@javamonkey 
sorry, 我只搜到了

> Escape:可以使用\ 做escape 符号，如\$monkey\$ 将作为一个普通的文本，输出为$monkey$.再如为了在后加上美元符号（占位符恰好又是美元符号）可以用这俩种方式hello,it’s $money$\$, 或者Hello,it’s $money+"\$"$ 。如果要输出\符号本生，则需要用俩个\,这点与javascript，java 语义一致.

似乎不是我需要的，我希望输入是 `<div>` 模板输出是 `&lt;div&gt;`

**Comment by javamonkey** [comment]
不是语法级解决，可以加个格式化函数就行了
${"<div>",escape}
