### ISSUE TITLE
关于自定义 cache 

### ISSUE THREAD

**Issue by laiyy0728** [javamonkey/beetl2.0#392]
在当前源码基础上，实现自定义 cache 时，在 web 项目中，由于在关联了 WebAppClassLoader，而其无法序列化，导致自定义 cache 实现失败。

cache 问题在一个项目多 tomcat 的情况下，会存在缓存不同步问题。触发清理模板缓存或刷新模板缓存的请求由NG分发到 A tomcat 上，然后获取模版缓存的请求由 NG 分发到 B tomcat 上，导致两个 tomcat 缓存不一致。是否可以实现自定义 cache 功能，多个项目使用同一个 cache 中心？

如：多个 tomcat 使用同一个 redis（集群），在读取 cache 时，从 redis 中读取并反序列化，在设置缓存时，序列化后添加到 redis 中。这样可以实现 cache 在多个 tomcat 中同步。

**Comment by javamonkey** [comment]
欢迎建议，实现，和PR，有什么想法可以继续讨论。 我想，不要从Cache入手，因为这个是一个JVM级别的缓存，无论如何都必须有，你可以实现一个ResourceLoader，比如RedisResourceLoader，用来加载模板和检测模板是否更新就可以了吧，如果模板更新，可以通过redis发一个消息给RedisResourceLoader，这个loader可以删除缓存，以及删除Cache里定义的模板ProgramMetaData

**Comment by laiyy0728** [comment]
恩，好的，我们通过消息来实现了这个功能，非常感谢~
